name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-api:
    name: API Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./apps/api/pnpm-lock.yaml

      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
        continue-on-error: true 

  check-web:
    name: Web Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web 
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./apps/web/pnpm-lock.yaml

      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
        continue-on-error: true